stages:
  - publish
PublishJob:
  tags:
    - publish
  stage: publish
  only:
    - /^.*/release$/
  script:
    - android_pipeline.sh publish -p=libcompiler -pd=/lib/libcompiler -g=com.wedoctor.android -a=leapflow-compiler -v=${MAJOR_VERSION}.${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-SNAPSHOT