stages:
  - publish
PublishJob:
  tags:
    - publish
  stage: publish
  only:
    - /^.*/release$/
  script:
    - android_pipeline.sh publish -p=libannotations -pd=/lib/libannotations -g=com.wedoctor.android -a=leapflow-annotation -v=${MAJOR_VERSION}.${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-SNAPSHOT