stages:
  - publish
PublishJob:
  tags:
    - publish
  stage: publish
  only:
    - /^.*/release$/
  script:
    - android_pipeline.sh publish -p=libleapflow -pd=/lib/libleapflow -g=com.wedoctor.android -a=leapflow -v=${MAJOR_VERSION}.${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-SNAPSHOT